
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package yu.ac.ns.ftn.informatika.ws.hello;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-13T01:42:30.911+02:00
 * Generated source version: 2.6.5
 * 
 */
public class HelloClient {

    public static void main(String[] args) throws Exception {
    	try {
			//kreiranje web servisa
			URL wsdlLocation = new URL("http://localhost:8080/poslovnaBanka/services/Hello?wsdl");
			QName serviceName = new QName("http://informatika.ftn.ns.ac.yu/ws/hello", "HelloService");
			QName portName = new QName("http://informatika.ftn.ns.ac.yu/ws/hello", "HelloPort");

			Service service = Service.create(wsdlLocation, serviceName);
			
			Hello hello = service.getPort(portName, Hello.class); 
			
			//poziv web servisa
			String response = hello.sayHi("Ako ovo radi, idem da spavam");
			System.out.println("Response from WS: " + response);
			
		} catch (MalformedURLException e) {
			e.printStackTrace();
		}
    }

}