
package rs.ac.uns.ftn.centralnabanka;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-22T17:19:52.185+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class CentralnaBanka_CentralnaBankaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/centralnaBanka", "CentralnaBankaService");

    private CentralnaBanka_CentralnaBankaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CentralnaBankaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CentralnaBankaService ss = new CentralnaBankaService(wsdlURL, SERVICE_NAME);
        CentralnaBanka port = ss.getCentralnaBankaPort();  
        
        {
        System.out.println("Invoking primiMT102...");
        rs.ac.uns.ftn.mt102.Mt102 _primiMT102_mt102 = null;
        rs.ac.uns.ftn.mt90010.TMT9 _primiMT102__return = port.primiMT102(_primiMT102_mt102);
        System.out.println("primiMT102.result=" + _primiMT102__return);


        }
        {
        System.out.println("Invoking primiMT103...");
        rs.ac.uns.ftn.mt103.MT103 _primiMT103_mt103 = null;
        rs.ac.uns.ftn.mt90010.TMT9 _primiMT103__return = port.primiMT103(_primiMT103_mt103);
        System.out.println("primiMT103.result=" + _primiMT103__return);


        }

        System.exit(0);
    }

}
