
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.centralnabanka;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-21T12:04:01.537+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "CentralnaBankaService",
                      portName = "CentralnaBankaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/centralnaBanka",
                      wsdlLocation = "file:/C:/Users/Tihomir/Documents/GitHub/XMLWS/Centralna_banka/WEB-INF/wsdl/CentralnaBanka.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.centralnabanka.CentralnaBanka")
                      
public class CentralnaBankaImpl implements CentralnaBanka {

    private static final Logger LOG = Logger.getLogger(CentralnaBankaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.centralnabanka.CentralnaBanka#primiMT102(rs.ac.uns.ftn.mt102.Mt102  mt102 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT102(rs.ac.uns.ftn.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.centralnabanka.CentralnaBanka#primiMT103(rs.ac.uns.ftn.mt103.MT103  mt103 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT103(rs.ac.uns.ftn.mt103.MT103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
