
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.banka;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-19T18:28:15.826+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "BankaService",
                      portName = "BankaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/Banka",
                      wsdlLocation = "/home/igor/Documents/gitRepos/XMLWS/Banka/Banka/WEB-INF/wsdl/Banka.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.banka.BankaPort")
                      
public class BankaPortImpl implements BankaPort {

    private static final Logger LOG = Logger.getLogger(BankaPortImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiMT102(rs.ac.uns.ftn.mt102.Mt102  mt102 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT102(rs.ac.uns.ftn.mt102.Mt102 mt102) { 
        LOG.info("Executing operation primiMT102");
        System.out.println(mt102);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiMT103(rs.ac.uns.ftn.mt103.MT103  mt103 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT103(rs.ac.uns.ftn.mt103.MT103 mt103) { 
        LOG.info("Executing operation primiMT103");
        System.out.println(mt103);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiZahtevZaIzvod(rs.ac.uns.ftn.zahtevzaizvod.ZahtevZaIzvod  zahtevZaIzvod )*
     */
    public rs.ac.uns.ftn.presek.Presek primiZahtevZaIzvod(rs.ac.uns.ftn.zahtevzaizvod.ZahtevZaIzvod zahtevZaIzvod) { 
        LOG.info("Executing operation primiZahtevZaIzvod");
        System.out.println(zahtevZaIzvod);
        try {
            rs.ac.uns.ftn.presek.Presek _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiMT900(rs.ac.uns.ftn.mt90010.TMT9  mt900 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT900(rs.ac.uns.ftn.mt90010.TMT9 mt900) { 
        LOG.info("Executing operation primiMT900");
        System.out.println(mt900);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiMT910(rs.ac.uns.ftn.mt90010.TMT9  mt910 )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiMT910(rs.ac.uns.ftn.mt90010.TMT9 mt910) { 
        LOG.info("Executing operation primiMT910");
        System.out.println(mt910);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#primiNalogZaPlacanje(rs.ac.uns.ftn.nalogzaprenos.NalogZaPrenos  nalogZaPrenos )*
     */
    public rs.ac.uns.ftn.xmlws.Status primiNalogZaPlacanje(rs.ac.uns.ftn.nalogzaprenos.NalogZaPrenos nalogZaPrenos) { 
        LOG.info("Executing operation primiNalogZaPlacanje");
        System.out.println(nalogZaPrenos);
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.banka.BankaPort#odradiClearing(*
     */
    public rs.ac.uns.ftn.xmlws.Status odradiClearing() { 
        LOG.info("Executing operation odradiClearing");
        try {
            rs.ac.uns.ftn.xmlws.Status _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
