
package rs.ac.uns.ftn.firma;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-20T01:53:20.999+02:00
 * Generated source version: 2.6.5
 * 
 */
public final class Firma_FirmaPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ftn.uns.ac.rs/firma", "FirmaService");

    private Firma_FirmaPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FirmaService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FirmaService ss = new FirmaService(wsdlURL, SERVICE_NAME);
        Firma port = ss.getFirmaPort();  
        
        {
        System.out.println("Invoking posaljiZahtevZaIzvod...");
        rs.ac.uns.ftn.zahtevzaizvod.ZahtevZaIzvod _posaljiZahtevZaIzvod_zahtevZaIzvod = null;
        rs.ac.uns.ftn.presek.Presek _posaljiZahtevZaIzvod__return = port.posaljiZahtevZaIzvod(_posaljiZahtevZaIzvod_zahtevZaIzvod);
        System.out.println("posaljiZahtevZaIzvod.result=" + _posaljiZahtevZaIzvod__return);


        }
        {
        System.out.println("Invoking posaljiNalogZaPrenos...");
        rs.ac.uns.ftn.nalogzaprenos.NalogZaPrenos _posaljiNalogZaPrenos_nalogZaPrenos = null;
        port.posaljiNalogZaPrenos(_posaljiNalogZaPrenos_nalogZaPrenos);


        }

        System.exit(0);
    }

}
