
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package rs.ac.uns.ftn.firma;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.6.5
 * 2017-06-20T01:53:21.102+02:00
 * Generated source version: 2.6.5
 * 
 */

@javax.jws.WebService(
                      serviceName = "FirmaService",
                      portName = "FirmaPort",
                      targetNamespace = "http://www.ftn.uns.ac.rs/firma",
                      wsdlLocation = "file:/C:/Users/skilj/Desktop/Firma/WEB-INF/wsdl/Firma.wsdl",
                      endpointInterface = "rs.ac.uns.ftn.firma.Firma")
                      
public class FirmaImpl implements Firma {

    private static final Logger LOG = Logger.getLogger(FirmaImpl.class.getName());

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.firma.Firma#posaljiZahtevZaIzvod(rs.ac.uns.ftn.zahtevzaizvod.ZahtevZaIzvod  zahtevZaIzvod )*
     */
    public rs.ac.uns.ftn.presek.Presek posaljiZahtevZaIzvod(rs.ac.uns.ftn.zahtevzaizvod.ZahtevZaIzvod zahtevZaIzvod) { 
        LOG.info("Executing operation posaljiZahtevZaIzvod");
        System.out.println(zahtevZaIzvod);
        try {
            rs.ac.uns.ftn.presek.Presek _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see rs.ac.uns.ftn.firma.Firma#posaljiNalogZaPrenos(rs.ac.uns.ftn.nalogzaprenos.NalogZaPrenos  nalogZaPrenos )*
     */
    public void posaljiNalogZaPrenos(rs.ac.uns.ftn.nalogzaprenos.NalogZaPrenos nalogZaPrenos) { 
        LOG.info("Executing operation posaljiNalogZaPrenos");
        System.out.println(nalogZaPrenos.getDuznik());
        /*
         * Treba napraviti konekciju ka mandicevom servisu i poslati mu objekat
         * */
        try {
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
